### ISSUE TITLE
Checklist for good quality Open Source Software 

### ISSUE THREAD

**Issue by bebatut** [chensy96/Galaxy-History-Test-Tool#1]
# Best practices for Python codes

- [ ] `requirements.txt` file with list of dependencies
- [ ] Project structure ([guide](https://docs.python-guide.org/writing/structure/))
- [ ] Code style ([guide](https://docs.python-guide.org/writing/style/)
  - [ ] Run `flake8` or `black`
- [ ] Testing ([guide](https://docs.python-guide.org/writing/tests/))
  - [ ] Unit test
  - [ ] Automated tests verifying the functionality of the software
- [ ] Continuous integration with GitHub Action
  - [ ] Automated tests
  - [ ] Code style
- [ ] Packaging ([guide](https://packaging.python.org/en/latest/overview/))

# General best practices

- [ ] `LICENSE` file: A plain-text  file with the contents of an OSI approved software license
- [ ] `CONTRIBUTING.md` file: Clear guidelines for third parties wishing to contribute to the software 
- [ ] Versioning & DOI
  - [ ] Connect repository to archiving tool like [Zenodo](https://guides.github.com/activities/citable-code/)
  - [ ] Generate releases often
- Documentation ([guide](https://docs.python-guide.org/writing/documentation/))
  - [ ] `README.md`
  - [ ] Documentation together with the code: [GitHub page](https://pages.github.com/), [ReadTheDoc](https://readthedocs.org/)
  - [ ] A statement of need: Section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is
  - [ ] Installation instructions: Clearly-stated list of dependencies, installation guideline
  - [ ] Example usage: Examples of how to use the software (ideally to solve real-world analysis problems).
  - [ ] Functionality documentation: Documentation of the core functionality of the software documented to a satisfactory level (e.g., API method documentation)
  - [ ] API documentation inside the functions

**Comment by YedilSerzhan** [comment]
Thanks, it's very comprehensive. 

I think for the code style it's worth mentioning [PEP 8](https://peps.python.org/pep-0008/), the standard style guide for python development.  The tools flake8 and black are based on it.

In my opinion, the file gitignore is also very important. There are usually some untracked files you want git to ignore.

**Comment by bebatut** [comment]
Thanks! I updated with your suggestions

**Comment by teresa-m** [comment]
Thanks a lot @bebatut! It is a very comprehensive collection. I think it could be shared with every student starting a project as a guideline for best practice. What do you think?
Maybe then we could add a small section on how to work with git to the general good practices?
- [ ] Use [git and GitHub ](https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)
- [ ] add a description of your project to the readme or a different file
- [ ] document intermediate results like plots or screenshots in the readme or a different file (e.g. [overleave](https://www.overleaf.com) )
